lecture_13/lecture_12/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('user.urls')),
    path('', include('blogs.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

lecture_13/user/urls.py
from django.urls import path
from user.views import login_page, register_page, logout_page, settings_page

urlpatterns = [
    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('logout', logout_page, name='logout'),
    path('settings/', settings_page, name='settings_page')
]

lecture_13/user/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    bio = models.CharField(null=False, blank=True, default='', max_length=255)
    owner = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', max_length=1000, null=True)
    resume = models.FileField(upload_to='files/', max_length=1000, null=True)

lecture_13/user/forms.py
from django.forms import Form, ModelForm
from django.contrib.auth.models import User
from user.models import Profile
from django import forms


class LoginForm(Form):
    username = forms.CharField(required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter username'}))
    password = forms.CharField(required=True,
                               widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'placeholder': 'Enter your password'}))


class UserRegistrationForm(ModelForm):
    repeat_password = forms.CharField(min_length=8, max_length=20, required=True,
                                      widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                        'placeholder': 'Repeat your password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your surname'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'}),
        }

    def clean_repeat_password(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("repeat_password")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['bio']
        widgets = {
            'bio': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Type something about yourself...'}),
        }

lecture_13/user/views.py
from django.shortcuts import render, redirect
from user.forms import UserRegistrationForm, LoginForm, ProfileForm
from django.contrib.auth.models import auth
from django.contrib.auth import login, logout
from user.models import Profile


def login_page(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'user/login.html', {'form': form})
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.data.get('username')
            password = form.data.get('password')
            user = auth.authenticate(username=username, password=password)
            try:
                profile = Profile.objects.get(owner_id=user.id)
            except:
                profile = Profile(owner_id=user.id)
                profile.save()
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'user/login.html', {'form': form})


def register_page(request):
    if request.method == 'GET':
        form = UserRegistrationForm()
        return render(request, 'user/registration.html', {'form': form})
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.save()
            profile = Profile(owner_id=user.id)
            profile.save()
            password = form.data.get('password')
            auth_data = auth.authenticate(request, email=user.email, password=password)
            login(request, user)
            if auth_data is not None:
                return redirect('/')
            return redirect('/auth/login/')
        else:
            return render(request, 'user/registration.html', {'form': form})


def logout_page(request):
    logout(request)
    return redirect('/auth/login/')


def settings_page(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            profile = Profile.objects.get(owner_id=request.user.id)
            form = ProfileForm(data={'bio': profile.bio}, files={'image': profile.image, 'resume': profile.resume})
            return render(request, 'user/profile.html', {'profile': profile, 'form': form})
        if request.method == 'POST':
            form = ProfileForm(request.POST, request.FILES)
            profile = Profile.objects.get(owner_id=request.user.id)
            if form.is_valid():
                profile.bio = form.data.get('bio')
                profile.image = form.files.get('image')
                profile.resume = form.files.get('resume')
                profile.save()
                return render(request, 'user/profile.html', {'profile': profile, 'form': form})
            else:
                return render(request, 'user/profile.html', {'profile': profile, 'form': form})
    else:
        return redirect('/')

lecture_13/user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <title>Login</title>
  <style>
      .field-wrapper {
        margin-top: 10px;
        margin-bottom: 10px;
      }

      .login-row {
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
      }
  </style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 login-row">
            <div class="col-12">
                <form name="login" method="POST" novalidate>
                  <h2>Login</h2>
                  {% csrf_token %}
                    {% for field in form %}
                        <div class="field-wrapper">
                            {{ field.label_tag }} {{ field }}
                            <div class="text-danger">
                            {{ field.errors }}
                            </div>
                        </div>
                    {% endfor %}
                  <button class="btn btn-primary d-block col-12" type="submit">Login</button>
                    <a href="/auth/register/" class="d-block text-center mt-4">You dont have an account? Register.</a>
            </form>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

lecture_13/user/templates/user/profile.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <title>Edit Profile</title>
  <style>
      .field-wrapper {
        margin-top: 10px;
        margin-bottom: 10px;
      }

      .image-wrapper {
        width: 100px;
        height: 100px;
        border-radius: 50%;
        background: #E8E8E8;
        overflow: hidden;
      }
      .image-wrapper img {
        width: 100%;
        height: 100%;
        object-fit: cover;
      }

      .image-wrapper input[type="file"] {
        width: 0;
        height: 0;
        overflow: hidden;
        visibility: 0;
      }
  </style>
{% endblock %}
{% block content %}
<div class="container">
    {% include 'nav.html' %}
    <div class="row">
        <div class="col-12">
            <div class="col-12">
                <form name="create_blog" method="POST" novalidate enctype="multipart/form-data">
              <h2>Create new blog</h2>
              {% csrf_token %}
                    <div class="field-wrapper">
                        <label for="id_image">
                            <div class="image-wrapper" id="image-wrapper">
                                {% if profile.image %}
                                    <img src="{{ profile.image.url }}" class="profile-image" id="profile-image"/>
                                {% endif %}
                                <input type="file" id="id_image" name="image" accept="image/*" />
                            </div>
                        </label>
                        <div class="text-danger">
                            {{ form.image.errors }}
                        </div>
                    </div>
                    <div class="field-wrapper">
                        {{ form.bio.label_tag }} {{ form.bio }}
                        <div class="text-danger">
                        {{ form.bio.errors }}
                        </div>
                    </div>
                    <div class="field-wrapper">
                        <input class="form-control" type="file" name="resume" id="id_resume">
                        <div class="text-danger">
                        {{ form.resume.errors }}
                        </div>
                    </div>
                    <div>
                        {% if profile.resume %}
                            <a href="{{ profile.resume.url }}" target="_blank">My resume</a>
                        {% endif %}
                    </div>
              <button class="btn btn-primary d-block col-12" type="submit">Create</button>
            </form>
            </div>
        </div>
    </div>
  </div>
  <script>
    const imageInput = document.getElementById('id_image');
    imageInput.onchange = (event) => {
      const files = imageInput.files;
      const file = files[0];
      const img = document.getElementById('profile-image');
      const wrapper = document.getElementById('image-wrapper');
      const newURL = URL.createObjectURL(file);
      if (img) {
        const newURL = URL.createObjectURL(file);
        img.src = newURL;
      } else {
        const newImg = document.createElement('IMG');
        newImg.src = newURL;
        newImg.id = 'profile-image';
        newImg.className = 'profile-image';
        wrapper.appendChild(newImg);
      }
    }
  </script>
{% endblock %}

lecture_13/user/templates/user/registration.html
{% extends 'base.html' %}

{% block head %}
    <title>Registration</title>
    <style>
        .login-row {
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .field-wrapper {
            margin-top: 10px;
            margin-bottom: 10px;
        }
    </style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 login-row">
            <div class="col-12">
            <form name="register" method="POST" novalidate>
              <h2>Registration</h2>
              {% csrf_token %}
                {% for field in form %}
                    <div class="field-wrapper">
                        {{ field.label_tag }} {{ field }}
                         {% if field.errors|length %}
                            <div class="text-danger">
                                {{ field.errors }}
                            </div>
                         {% endif %}
                    </div>
                {% endfor %}
              <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
            </form>
            <a href="/auth/login/" class="block">Already signed? Login</a>
            </div>
        </div>
    </div>
  </div>
{% endblock %}